% quick guestimation of size

frame(1:300) = struct('time', GetSecs, 'push_data', eye(20, 10), 'state', '', ...
               'beep4', 0, 'image', 0);

trial(1:length(1:100)) = struct('frame', frame, 'rel_start', [], ...
                                    'resp1', [], 't_resp1', [], 'img_index', ...
                                    [], 'finger_index', [], 'correct', []);
block = struct('trial', trial, 'id', 3, 'shapes', 0);
