frame(1:180) = struct('time', GetSecs, 'push_data', [], 'state', '', ...
               'beep4', 0, 'image', 0);

trial(1:length(tgt.trial)) = struct('frame', frame, 'rel_start', [], ...
                                    'resp1', [], 't_resp1', [], 'img_index', ...
                                    [], 'finger_index', [], 'correct');
block = struct('trial', trial, 'id', id, 'shapes', 0);
